import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // eslint-config-next ships `settings.react.version: "detect"`, which
    // makes eslint-plugin-react call `context.getFilename()` to
    // auto-detect the React version — a legacy ESLint context method that
    // no longer exists as of ESLint 10, crashing every rule that reads the
    // React version (react/display-name, etc.) with "getFilename is not a
    // function". eslint-plugin-react's latest release (7.37.5) still only
    // supports ESLint up to ^9.7, so pinning the version explicitly here
    // (skipping the broken auto-detect branch entirely) is the workaround
    // until it catches up.
    settings: { react: { version: "19.2.4" } },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Agent-skill scaffolding (bundled examples, not app code — matches
    // tsconfig.json's exclude) and stray worktree checkouts under .claude,
    // which each carry their own eslint.config.mjs/node_modules that would
    // otherwise get picked up by a recursive lint run.
    "agent/**",
    ".agents/**",
    ".claude/**",
    ".windsurf/**",
    // Prisma's generated client/runtime — regenerated by `prisma
    // generate`, not hand-written, and largely minified/bundled code that
    // isn't meaningfully lintable as app source.
    "generated/**",
  ]),
]);

export default eslintConfig;
